# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script' 


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: MSBuild@1
  inputs:
    solution: 'solution1.sln'
    platform: '$(platform)'
    configuration: '$(Configuration)'
 
- task: MSBuild@1
  inputs:
    solution: 'solution2.sln'
    platform: '$(platform)'
    configuration: '$(Configuration)'